# mitigation:
#   Настройки "мягкого" противодействия читам. Вместо мгновенного наказания,
#   анти-чит может, например, временно урезать урон игрока.
#
# punishment-key:
# Ключ, который связывает эту проверку с блоком наказания в файле punish.yml.
#
# Все остальные параметры - это "чувствительность" проверки.
# Изменяйте их с осторожностью Если вы наблюдаете ложные срабатывания (фолсы),
# попробуйте немного увеличить значения порогов (например, min-acceleration с 10.0 до 12.0).

# Настройки оповещений для персонала
alerts:
  # Право, необходимое игроку, чтобы видеть оповещения о нарушениях.
  permission: "shadeac.alerts"

  # Формат сообщения об оповещении.
  # Доступные плейсхолдеры:
  # %player% - Имя игрока
  # %check% - Название проверки (e.g., Killaura)
  # %type% - Тип проверки (e.g., A, B)
  # %vl% - Уровень нарушений (Violations Level)
  # %debug% - Дополнительная отладочная информация от проверки
  message: "&8[&3ShadeAc&8] &7» &b%player% &fнарушает &3%check% &7(&b%type%&7) &fVL: &b%vl% &8[&7%debug%&8]"

# Настройки проверок
checks:
  combat:
    killaura:
      # Проверка A: Анализ "снапов" (резких и точных доводок к цели).
      A:
        enabled: true
        # Минимальный угол до цели *перед* доводом, чтобы он считался коррекцией (в градусах).
        min-correction-angle: 5.0
        # Максимальный угол до цели *после* довода, чтобы он считался точным.
        max-final-angle: 0.8
        # Минимальное ускорение (разница скоростей поворота), чтобы движение считалось резким.
        min-acceleration: 10.0

        mitigation:
          enabled: true
          # Режимы: CANCEL_HITS (отмена ударов), REDUCE_DAMAGE (урезание урона), NONE (выключено).
          mode: "CANCEL_HITS"
          # Длительность митигации в секундах после одного нарушения.
          duration-seconds: 5

        punishment-key: "killaura-a-punishment"

      # Проверка B: Эвристический анализ паттернов прицеливания (волатильность, рывок).
      B:
        enabled: true
        # Количество пакетов для анализа. Не рекомендуется изменять.
        sample-size: 210
        # Порог "провалов" микро-анализа для срабатывания.
        fails-threshold: 7
        # Порог "волатильности" (общей "энергии" движений мыши).
        volatility-threshold: 120
        # Порог "рывка" (резкости изменения ускорения).
        jerk-threshold: 60

        mitigation:
          enabled: false
          mode: "NONE"

        punishment-key: "killaura-b-punishment"

    aim:
      # Проверка A: Анализ плавности (простой Aim).
      A:
        enabled: true
        # Максимальное стандартное отклонение. Чем ниже, тем плавнее прицел.
        max-deviation: 0.09
        # Максимальный "рывок". Низкие значения также указывают на неестественную плавность.
        max-jerk: 0.12

        mitigation:
          enabled: true
          mode: "REDUCE_DAMAGE"
          duration-seconds: 3
          reduce-amount: 0.3

        punishment-key: "aim-a-punishment"

      # Проверка B: Анализ корреляции (насколько движения игрока "копируют" идеальные)
      # и распределения ошибок. Эффективна против Smooth/Silent Aim.
      B:
        enabled: true
        # Минимальная корреляция для срабатывания (1.0 = идеально).
        min-correlation: 0.98
        # Границы для куртозиса (характера ошибок прицеливания).
        max-kurtosis: 0.5
        min-kurtosis: -0.5

        mitigation:
          enabled: true
          mode: "REDUCE_DAMAGE"
          duration-seconds: 4
          # Урез урон на 60%
          reduce-amount: 0.6

        punishment-key: "aim-b-punishment"