name: ShadeAc
version: 1.0
main: ru.Fronzter.ShadeAc.ShadeAc
api-version: 1.16
depend: [PacketEvents]
authors: [Fronzter]
website: https://t.me/Fronzter
license: GPL-3.0
description: "ShadeAc – open-source anti-cheat plugin with machine learning."
commands:
  shadeac:
    permission: shadeac.admin
    aliases: [sac]

  shadeacpunish:
    permission: shadeac.punish
    aliases: [sapunish, shapunish]

  shadeacml:
    permission: shadeac.ml.admin
    aliases: [sacml]
