name: ShadeAc
version: 1.0
main: ru.Fronzter.ShadeAc.ShadeAc
api-version: 1.16
authors: [Fronzter]
softdepend: [ProtocolLib]
website: https://t.me/Fronzter
license: GPL-3.0
description: "ShadeAc – open-source anti-cheat plugin."
commands:
  shadeac:
    description: "Основная команда анти-чита ShadeAc."
    usage: "/<command> [reload|alerts|punish]"
    aliases: [sac]